export * from './account.service';
import { AccountService } from './account.service';
export * from './addOns.service';
import { AddOnsService } from './addOns.service';
export * from './apo.service';
import { ApoService } from './apo.service';
export * from './availability.service';
import { AvailabilityService } from './availability.service';
export * from './booking.service';
import { BookingService } from './booking.service';
export * from './bookingboardingpasses.service';
import { BookingboardingpassesService } from './bookingboardingpasses.service';
export * from './bookingcheckin.service';
import { BookingcheckinService } from './bookingcheckin.service';
export * from './bookingcontacts.service';
import { BookingcontactsService } from './bookingcontacts.service';
export * from './bookingjourneys.service';
import { BookingjourneysService } from './bookingjourneys.service';
export * from './bookingpassengers.service';
import { BookingpassengersService } from './bookingpassengers.service';
export * from './bookingpayments.service';
import { BookingpaymentsService } from './bookingpayments.service';
export * from './bookingretrieve.service';
import { BookingretrieveService } from './bookingretrieve.service';
export * from './bookings.service';
import { BookingsService } from './bookings.service';
export * from './bookingssrs.service';
import { BookingssrsService } from './bookingssrs.service';
export * from './bundles.service';
import { BundlesService } from './bundles.service';
export * from './collection.service';
import { CollectionService } from './collection.service';
export * from './configuration.service';
import { ConfigurationService } from './configuration.service';
export * from './currency.service';
import { CurrencyService } from './currency.service';
export * from './fareRules.service';
import { FareRulesService } from './fareRules.service';
export * from './graph.service';
import { GraphService } from './graph.service';
export * from './health.service';
import { HealthService } from './health.service';
export * from './manifest.service';
import { ManifestService } from './manifest.service';
export * from './messages.service';
import { MessagesService } from './messages.service';
export * from './oneTimeTravelNotifications.service';
import { OneTimeTravelNotificationsService } from './oneTimeTravelNotifications.service';
export * from './organizations.service';
import { OrganizationsService } from './organizations.service';
export * from './organizations2.service';
import { Organizations2Service } from './organizations2.service';
export * from './persons.service';
import { PersonsService } from './persons.service';
export * from './promotions.service';
import { PromotionsService } from './promotions.service';
export * from './queues.service';
import { QueuesService } from './queues.service';
export * from './redirect.service';
import { RedirectService } from './redirect.service';
export * from './redis.service';
import { RedisService } from './redis.service';
export * from './resources.service';
import { ResourcesService } from './resources.service';
export * from './seatmaps.service';
import { SeatmapsService } from './seatmaps.service';
export * from './settings.service';
import { SettingsService } from './settings.service';
export * from './token.service';
import { TokenService } from './token.service';
export * from './trip.service';
import { TripService } from './trip.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './userperson.service';
import { UserpersonService } from './userperson.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './utilities.service';
import { UtilitiesService } from './utilities.service';
export * from './voucherIssuance.service';
import { VoucherIssuanceService } from './voucherIssuance.service';
export * from './vouchers.service';
import { VouchersService } from './vouchers.service';
export const APIS = [AccountService, AddOnsService, ApoService, AvailabilityService, BookingService, BookingboardingpassesService, BookingcheckinService, BookingcontactsService, BookingjourneysService, BookingpassengersService, BookingpaymentsService, BookingretrieveService, BookingsService, BookingssrsService, BundlesService, CollectionService, ConfigurationService, CurrencyService, FareRulesService, GraphService, HealthService, ManifestService, MessagesService, OneTimeTravelNotificationsService, OrganizationsService, Organizations2Service, PersonsService, PromotionsService, QueuesService, RedirectService, RedisService, ResourcesService, SeatmapsService, SettingsService, TokenService, TripService, UserService, UserpersonService, UsersService, UtilitiesService, VoucherIssuanceService, VouchersService];
