/**
 * API - Current Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: trunk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { GraphQlQuery } from '../model/graphQlQuery';
import { GraphQlQueryv2 } from '../model/graphQlQueryv2';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class GraphService {

    protected basePath = 'https://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Invokes a graph query configured in utilities.
     * When a graph query is configured on the server under Resource Management it allows your payload sizes to be even smaller.
     * @param queryName The query name matching your resource management configuration.
     * @param cachedResults True to return cached results.
     * @param variables The json matching your json variables in your graph query.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiNskV1GraphByQueryNamePost(queryName: string, cachedResults: boolean, variables?: any, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiNskV1GraphByQueryNamePost(queryName: string, cachedResults: boolean, variables?: any, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiNskV1GraphByQueryNamePost(queryName: string, cachedResults: boolean, variables?: any, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiNskV1GraphByQueryNamePost(queryName: string, cachedResults: boolean, variables?: any, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (queryName === null || queryName === undefined) {
            throw new Error('Required parameter queryName was null or undefined when calling apiNskV1GraphByQueryNamePost.');
        }

        if (cachedResults === null || cachedResults === undefined) {
            throw new Error('Required parameter cachedResults was null or undefined when calling apiNskV1GraphByQueryNamePost.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (cachedResults !== undefined && cachedResults !== null) {
            queryParameters = queryParameters.set('cachedResults', <any>cachedResults);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/api/nsk/v1/graph/${encodeURIComponent(String(queryName))}`,
            variables,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param query 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV1GraphPost(query?: GraphQlQuery, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiV1GraphPost(query?: GraphQlQuery, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiV1GraphPost(query?: GraphQlQuery, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiV1GraphPost(query?: GraphQlQuery, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/api/v1/graph`,
            query,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param queryName 
     * @param query 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2GraphByQueryNamePost(queryName: string, query?: GraphQlQueryv2, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiV2GraphByQueryNamePost(queryName: string, query?: GraphQlQueryv2, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiV2GraphByQueryNamePost(queryName: string, query?: GraphQlQueryv2, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiV2GraphByQueryNamePost(queryName: string, query?: GraphQlQueryv2, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (queryName === null || queryName === undefined) {
            throw new Error('Required parameter queryName was null or undefined when calling apiV2GraphByQueryNamePost.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/api/v2/graph/${encodeURIComponent(String(queryName))}`,
            query,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
