/**
 * API - Current Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: trunk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PassengerSsrAvailability } from './passengerSsrAvailability';


/**
 * Get the passenger keys this is available for
 */
import * as Enums from '../enums';

import {Dictionary} from "lodash"; export type BundleLegSsrPassengersAvailability =  Dictionary<PassengerSsrAvailability>
