/**
 * API - Current Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: trunk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * The organization account transaction request.
 */
import * as Enums from '../enums';

export interface ChildAccountTransactionsRequest { 
    /**
     * The amount to adjust on the account.
     */
    amount: number;
}
