/**
 * API - Current Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: trunk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelError } from './modelError';


import * as Enums from '../enums';

export interface ModelStateEntry { 
    rawValue?: any;
    attemptedValue?: string;
    readonly errors?: Array<ModelError>;
    validationState?: 'Unvalidated'|'Invalid'|'Valid'|'Skipped';
    readonly isContainerNode?: boolean;
    readonly children?: Array<ModelStateEntry>;
}
