/**
 * API - Current Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: trunk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { VoucherSummary } from './voucherSummary';


/**
 * The voucher by date search response item.
 */
import * as Enums from '../enums';

export interface VouchersSummaryResponse { 
    /**
     * The key for the last item returned from paging.
     */
    lastPageKey?: string;
    /**
     * The collection of vouchers.
     */
    vouchers?: Array<VoucherSummary>;
}
