/**
 * API - Current Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: trunk
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * The aggregate collection of fares available for all trips.
 */
import Dictionary from "lodash";
import { FareAvailability } from "./fareAvailability";

export type AvailabilityFaresAvailable = Dictionary<FareAvailability>;
