/**
 * API - Current Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: trunk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SegmentTripResult } from './segmentTripResult';


/**
 * Booking flight result data.
 */
export interface BookingTripResult { 
    /**
     * The record locator.
     */
    recordLocator?: string;
    /**
     * The booking status.
     */
    bookingStatus?: BookingTripResult.BookingStatusEnum;
    /**
     * The price status.
     */
    priceStatus?: BookingTripResult.PriceStatusEnum;
    /**
     * The paid status.
     */
    paidStatus?: BookingTripResult.PaidStatusEnum;
    /**
     * The UTC date and time of when the booking was created.
     */
    createdDate?: Date;
    /**
     * The first name on the booking.
     */
    firstName?: string;
    /**
     * The last name on the booking.
     */
    lastName?: string;
    /**
     * The customer number on the booking.
     */
    customerNumber?: string;
    /**
     * The applicable segments.
     */
    segments?: Array<SegmentTripResult>;
}
export namespace BookingTripResult {
    export type BookingStatusEnum = 'Default' | 'Hold' | 'Confirmed' | 'Closed' | 'HoldCanceled' | 'PendingArchive' | 'Archived';
    export type PriceStatusEnum = 'Invalid' | 'Override' | 'Valid';
    export type PaidStatusEnum = 'UnderPaid' | 'PaidInFull' | 'OverPaid';
}
