/**
 * API - Current Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: trunk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PassengerSeatGroupInfo } from './passengerSeatGroupInfo';


/**
 * The collection passenger seat group fees to go along with the collection of seat maps.
 */
export interface SeatMapAvailabilityFees { 
    ?: PassengerSeatGroupInfo;
}
