/**
 * API - Current Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: trunk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Defines a boarding pass transportation designator.
 */

export interface BoardingPassTransportationDesignator { 
    /**
     * The destination stations localized name.
     */
    destinationStationName?: string;
    /**
     * Gets or sets the leg arrival station.
     */
    destination?: string;
    /**
     * The origin stations localized name.
     */
    originStationName?: string;
    /**
     * Gets or sets the leg departure station.
     */
    origin?: string;
    /**
     * The arrival date and time local to the arrival station.
     */
    arrival?: Date;
    /**
     * The departure date and time local to the departure station.
     */
    departure?: Date;
}
