/**
 * API - Current Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: trunk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SegmentTripResult } from './segmentTripResult';


/**
 * Booking flight result data.
 */

    import { BookingTripResult<CAP>bookingStatus</CAP> } from '../types/enums';
    import { BookingTripResult<CAP>priceStatus</CAP> } from '../types/enums';
    import { BookingTripResult<CAP>paidStatus</CAP> } from '../types/enums';

export interface BookingTripResult { 
    /**
     * The record locator.
     */
    recordLocator?: string;
    /**
     * The booking status.
     */
    bookingStatus?: <ENUM>'Default'|'Hold'|'Confirmed'|'Closed'|'HoldCanceled'|'PendingArchive'|'Archived'</ENUM>;
    /**
     * The price status.
     */
    priceStatus?: <ENUM>'Invalid'|'Override'|'Valid'</ENUM>;
    /**
     * The paid status.
     */
    paidStatus?: <ENUM>'UnderPaid'|'PaidInFull'|'OverPaid'</ENUM>;
    /**
     * The UTC date and time of when the booking was created.
     */
    createdDate?: Date;
    /**
     * The first name on the booking.
     */
    firstName?: string;
    /**
     * The last name on the booking.
     */
    lastName?: string;
    /**
     * The customer number on the booking.
     */
    customerNumber?: string;
    /**
     * The applicable segments.
     */
    segments?: Array<SegmentTripResult>;
}
