/**
 * API - Current Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: trunk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Defines a connector type.
 */
export interface ConnectorType { 
    /**
     * The unique code for this connector type.
     */
    code: string;
    /**
     * The description.
     */
    description?: string;
    /**
     * The connector assembly.
     */
    assembly?: string;
}
