/**
 * API - Current Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: trunk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FeeRule } from './feeRule';
import { RegionFee } from './regionFee';


/**
 * Fee detail model.
 */

    import { FeeDetail<CAP>taxApplicationOverride</CAP> } from '../types/enums';
    import { FeeDetail<CAP>travelComponentOverride</CAP> } from '../types/enums';
    import { FeeDetail<CAP>feeApplicationOverride</CAP> } from '../types/enums';

export interface FeeDetail { 
    /**
     * Gets or sets the fee option number of this fee option.
     */
    number?: number;
    /**
     * Gets or sets the fee rules for this fee option.
     */
    feeRules?: Array<FeeRule>;
    /**
     * Gets or sets the name for this fee option.
     */
    name?: string;
    /**
     * Gets or sets the region fees for this fee option.
     */
    regionFees?: Array<RegionFee>;
    /**
     * Gets or sets the override of how to apply the taxes.
     */
    taxApplicationOverride?: <ENUM>'Unknown'|'Taxable'|'TaxableLocal'|'NonTaxable'|'NonTaxableApplyToBaseFareOnly'|'TaxableByTrip'|'TaxableByItinerary'</ENUM>;
    /**
     * Gets or sets the override for the travel component.
     */
    travelComponentOverride?: <ENUM>'Unknown'|'Itinerary'|'Trip'|'Journey'|'Segment'|'Leg'|'ItineraryWithJourneySalesDate'|'TripWithJourneySalesDate'|'JourneyWithBookingSalesDate'|'JourneyWithJourneySalesDate'|'SegmentWithJourneySalesDate'|'LegWithJourneySalesDate'|'Fare'</ENUM>;
    /**
     * Gets or sets the flag for using the overrides.
     */
    useOverrides?: boolean;
    /**
     * Gets or sets the override for where to apply this fee option.
     */
    feeApplicationOverride?: <ENUM>'Pnr'|'TravelComponent'|'EachPassenger'|'EachPassengerTravelComponent'|'SpecifyPassenger'|'AllPaxCheckingBagsTogether'|'PerBookingNoLimit'</ENUM>;
}
