/**
 * API - Current Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: trunk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Model information about the baggage a passenger has on a segment.
 */

    import { PassengerSegmentBag<CAP>status</CAP> } from '../models/enums';

export interface PassengerSegmentBag { 
    /**
     * Unique key for the baggage.
     */
    baggageKey?: string;
    /**
     * The passenger key associated to this bag.
     */
    passengerKey: string;
    /**
     * The bag segment arrival station.
     */
    arrivalStation: string;
    /**
     * The bag status.
     */
    status?: PassengerSegmentBag<CAP>status</CAP>;
    /**
     * The bag segment departure station.
     */
    departureStation: string;
    /**
     * The bag OS tag.
     */
    osTag?: string;
}
