/**
 * API - Current Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: trunk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Defines a person's alternate name that they go by.
 */

    import { PersonAlias<CAP>type<CAP> } from '../models/enums';

export interface PersonAlias { 
    /**
     * The unique person alias key.
     */
    personAliasKey?: string;
    /**
     * The type of alias.
     */
    type?: PersonAlias<CAP>type<CAP>;
    /**
     * The given first name.
     */
    first?: string;
    /**
     * The given middle name.
     */
    middle?: string;
    /**
     * The given last name.
     */
    last?: string;
    /**
     * The title.
     */
    title?: string;
    /**
     * The suffix.
     */
    suffix?: string;
}
