/**
 * API - Current Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: trunk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RoleSettingType } from './roleSettingType';


/**
 * The role settings model.
 */
import * as Enums from '../types/enums';

export interface RoleSetting { 
    /**
     * The number version of the data associated with this setting.
     */
    dataVersion?: number;
    /**
     * The setting data for this setting.
     */
    settingData?: string;
    /**
     * The setting type for this setting.
     */
    roleSettingType?: RoleSettingType;
}
