/**
 * API - Current Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: trunk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SsrByJourney } from './ssrByJourney';
import { SsrByLeg } from './ssrByLeg';
import { SsrBySegment } from './ssrBySegment';


/**
 * Model containing all Ssr information.
 */

export interface SsrAvailability { 
    /**
     * Journey Ssrs.
     */
    journeySsrs?: Array<SsrByJourney>;
    /**
     * Segment Ssrs.
     */
    segmentSsrs?: Array<SsrBySegment>;
    /**
     * Leg Ssrs.
     */
    legSsrs?: Array<SsrByLeg>;
}
