/**
 * API - Current Routes
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: trunk
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Represents the trip operation delay data.
 */
import * as Enums from '../types/enums';

export interface TripOperationDelay { 
    /**
     * The unique identification for the trip operation delay.
     */
    tripOperationDelayKey?: string;
    /**
     * The delay code.
     */
    delayCode?: string;
    /**
     * The number of minutes for this delay.
     */
    delayMinutes?: number;
    /**
     * The note for this delay, containing extra information about the delay  (if any).
     */
    note?: string;
    /**
     * The flag to include the MVT message.
     */
    includeMvtMessage?: boolean;
    /**
     * The date the status was created.
     */
    createdDate?: Date;
}
