import {interfaces} from "inversify";

import { AccountService } from './api/account.service';
import { AddOnsService } from './api/addOns.service';
import { ApoService } from './api/apo.service';
import { AvailabilityService } from './api/availability.service';
import { BookingService } from './api/booking.service';
import { BookingboardingpassesService } from './api/bookingboardingpasses.service';
import { BookingcheckinService } from './api/bookingcheckin.service';
import { BookingcontactsService } from './api/bookingcontacts.service';
import { BookingjourneysService } from './api/bookingjourneys.service';
import { BookingpassengersService } from './api/bookingpassengers.service';
import { BookingpaymentsService } from './api/bookingpayments.service';
import { BookingretrieveService } from './api/bookingretrieve.service';
import { BookingsService } from './api/bookings.service';
import { BookingssrsService } from './api/bookingssrs.service';
import { BundlesService } from './api/bundles.service';
import { CollectionService } from './api/collection.service';
import { ConfigurationService } from './api/configuration.service';
import { CurrencyService } from './api/currency.service';
import { FareRulesService } from './api/fareRules.service';
import { GraphService } from './api/graph.service';
import { HealthService } from './api/health.service';
import { ManifestService } from './api/manifest.service';
import { MessagesService } from './api/messages.service';
import { OneTimeTravelNotificationsService } from './api/oneTimeTravelNotifications.service';
import { OrganizationsService } from './api/organizations.service';
import { Organizations2Service } from './api/organizations2.service';
import { PersonsService } from './api/persons.service';
import { PromotionsService } from './api/promotions.service';
import { QueuesService } from './api/queues.service';
import { RedirectService } from './api/redirect.service';
import { RedisService } from './api/redis.service';
import { ResourcesService } from './api/resources.service';
import { SeatmapsService } from './api/seatmaps.service';
import { SettingsService } from './api/settings.service';
import { TokenService } from './api/token.service';
import { TripService } from './api/trip.service';
import { UserService } from './api/user.service';
import { UserpersonService } from './api/userperson.service';
import { UsersService } from './api/users.service';
import { UtilitiesService } from './api/utilities.service';
import { VoucherIssuanceService } from './api/voucherIssuance.service';
import { VouchersService } from './api/vouchers.service';

export class ApiServiceBinder {
    public static with(container: interfaces.Container) {
        container.bind<AccountService>("AccountService").to(AccountService).inSingletonScope();
        container.bind<AddOnsService>("AddOnsService").to(AddOnsService).inSingletonScope();
        container.bind<ApoService>("ApoService").to(ApoService).inSingletonScope();
        container.bind<AvailabilityService>("AvailabilityService").to(AvailabilityService).inSingletonScope();
        container.bind<BookingService>("BookingService").to(BookingService).inSingletonScope();
        container.bind<BookingboardingpassesService>("BookingboardingpassesService").to(BookingboardingpassesService).inSingletonScope();
        container.bind<BookingcheckinService>("BookingcheckinService").to(BookingcheckinService).inSingletonScope();
        container.bind<BookingcontactsService>("BookingcontactsService").to(BookingcontactsService).inSingletonScope();
        container.bind<BookingjourneysService>("BookingjourneysService").to(BookingjourneysService).inSingletonScope();
        container.bind<BookingpassengersService>("BookingpassengersService").to(BookingpassengersService).inSingletonScope();
        container.bind<BookingpaymentsService>("BookingpaymentsService").to(BookingpaymentsService).inSingletonScope();
        container.bind<BookingretrieveService>("BookingretrieveService").to(BookingretrieveService).inSingletonScope();
        container.bind<BookingsService>("BookingsService").to(BookingsService).inSingletonScope();
        container.bind<BookingssrsService>("BookingssrsService").to(BookingssrsService).inSingletonScope();
        container.bind<BundlesService>("BundlesService").to(BundlesService).inSingletonScope();
        container.bind<CollectionService>("CollectionService").to(CollectionService).inSingletonScope();
        container.bind<ConfigurationService>("ConfigurationService").to(ConfigurationService).inSingletonScope();
        container.bind<CurrencyService>("CurrencyService").to(CurrencyService).inSingletonScope();
        container.bind<FareRulesService>("FareRulesService").to(FareRulesService).inSingletonScope();
        container.bind<GraphService>("GraphService").to(GraphService).inSingletonScope();
        container.bind<HealthService>("HealthService").to(HealthService).inSingletonScope();
        container.bind<ManifestService>("ManifestService").to(ManifestService).inSingletonScope();
        container.bind<MessagesService>("MessagesService").to(MessagesService).inSingletonScope();
        container.bind<OneTimeTravelNotificationsService>("OneTimeTravelNotificationsService").to(OneTimeTravelNotificationsService).inSingletonScope();
        container.bind<OrganizationsService>("OrganizationsService").to(OrganizationsService).inSingletonScope();
        container.bind<Organizations2Service>("Organizations2Service").to(Organizations2Service).inSingletonScope();
        container.bind<PersonsService>("PersonsService").to(PersonsService).inSingletonScope();
        container.bind<PromotionsService>("PromotionsService").to(PromotionsService).inSingletonScope();
        container.bind<QueuesService>("QueuesService").to(QueuesService).inSingletonScope();
        container.bind<RedirectService>("RedirectService").to(RedirectService).inSingletonScope();
        container.bind<RedisService>("RedisService").to(RedisService).inSingletonScope();
        container.bind<ResourcesService>("ResourcesService").to(ResourcesService).inSingletonScope();
        container.bind<SeatmapsService>("SeatmapsService").to(SeatmapsService).inSingletonScope();
        container.bind<SettingsService>("SettingsService").to(SettingsService).inSingletonScope();
        container.bind<TokenService>("TokenService").to(TokenService).inSingletonScope();
        container.bind<TripService>("TripService").to(TripService).inSingletonScope();
        container.bind<UserService>("UserService").to(UserService).inSingletonScope();
        container.bind<UserpersonService>("UserpersonService").to(UserpersonService).inSingletonScope();
        container.bind<UsersService>("UsersService").to(UsersService).inSingletonScope();
        container.bind<UtilitiesService>("UtilitiesService").to(UtilitiesService).inSingletonScope();
        container.bind<VoucherIssuanceService>("VoucherIssuanceService").to(VoucherIssuanceService).inSingletonScope();
        container.bind<VouchersService>("VouchersService").to(VouchersService).inSingletonScope();
    }
}
